version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: notes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notes
  # test-db:
  #   image: postgres
  #   ports:
  #     - 5434:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: notes
